apiVersion: v1
kind: ConfigMap
metadata:
  name: arkhe-config
  labels:
    app.kubernetes.io/name: arkhe-benchmark
    app.kubernetes.io/part-of: arkhe-sentinel-ecosystem
data:
  PORT: "8080"
  PYTHONUNBUFFERED: "1"
  OTEL_CONSOLE_EXPORT: "false"
  TARGET_TPS: "80"
  TARGET_URL: "http://arkhe-card-auth-lab-service:8080/v1/charge"
