apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: arkhe-sentinel-ecosystem

resources:
  - configmap.yaml
  - service-lab.yaml
  - deployment-lab.yaml
  - deployment-loadgen.yaml
  - hpa.yaml
  - ingress.yaml
